### ISSUE TITLE
Support for Debezium verion 2.7 and over

### ISSUE THREAD

**Issue by lafod** [aws-samples/msk-connect-custom-plugin-jmx#3]
The current library does not support Debezium version 2.7 because of the missing file  MySqlStreamingChangeEventSourceMetricsMXBean

kafka-connect-1  | 2024-10-10 08:30:54,609 INFO   ||  JMX URL : service:jmx:rmi://localhost/jndi/rmi://localhost:7098/jmxrmi   [com.amazonaws.msk.debezium.mysql.connect.JMXMetricsExporter]
kafka-connect-1  | 2024-10-10 08:30:54,634 INFO   ||  Connected to JMX Server Successfully   [com.amazonaws.msk.debezium.mysql.connect.JMXMetricsExporter]
kafka-connect-1  | 2024-10-10 08:30:54,635 INFO   ||  Object Name : debezium.mysql:type=connector-metrics,context=streaming,server=   [com.amazonaws.msk.debezium.mysql.connect.JMXMetricsExporter]
kafka-connect-1  | Exception in thread "Timer-0" java.lang.NoClassDefFoundError: io/debezium/connector/mysql/MySqlStreamingChangeEventSourceMetricsMXBean
kafka-connect-1  |      at com.amazonaws.msk.debezium.mysql.connect.JMXMetricsExporter.getMSBehindSourceMetric(JMXMetricsExporter.java:102)
kafka-connect-1  |      at com.amazonaws.msk.debezium.mysql.connect.JMXMetricsExporter.run(JMXMetricsExporter.java:41)
kafka-connect-1  |      at com.amazonaws.msk.debezium.mysql.connect.Scheduler$1.run(Scheduler.java:16)
kafka-connect-1  |      at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
kafka-connect-1  |      at java.base/java.util.TimerThread.run(Timer.java:516)
kafka-connect-1  | Caused by: java.lang.ClassNotFoundException: io.debezium.connector.mysql.MySqlStreamingChangeEventSourceMetricsMXBean
kafka-connect-1  |      at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
kafka-connect-1  |      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
kafka-connect-1  |      at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:124)
kafka-connect-1  |      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
kafka-connect-1  |      ... 5 more

**Comment by techy-sharmila** [comment]
Resolved with the branch: https://github.com/aws-samples/msk-connect-custom-plugin-jmx/tree/2.7/
